maxPlayer: 100  # 플레이어 접속 제한 인원

joinBlockedMOTD: "&c&l현재 서버 정원이 가득 찼습니다. 잠시만 기다려주세요." # 대기중인 플레이어가 없지만 서버 정원이 가득 찼을 때 MOTD
waitLineMOTD: "&b&l플레이어님 앞에 %remainPlayer%명이 대기중입니다." # 대기중 일때 뜨는 MOTD
enterMOTD: "&c&l플레이어님의 순서입니다. %remainTime%초 안에 접속하지 않으면 다음 플레이어에게 차례가 넘어갑니다!" # 플레이어의 차례가 왔을때 뜨는 MOTD

kickMessage: "&c서버 정원이 가득 차 대기열에 등록되었습니다. 서버 설명을 새로고침하여 확인 해주세요." # 대기열에 등록되었을 때 메시지
kickMessageWaiting: "아직 차례가 되지 않았습니다. 서버 설명(MOTD)에서 본인의 차례를 확인하세요!" # 대기열에 등록되었지만 접속에 실패했을 때

enterTime: 180 # 순서가 다가왔을때 해당 시간 이후까지 접속하지 않으면 다음 플레이어에게 순서가 넘어갑니다. (단위: 초)