maxPlayer: 100  # 플레이어 접속 제한 인원

enterTime: 180 # 순서가 다가왔을때 해당 시간 이후까지 접속하지 않으면 다음 플레이어에게 순서가 넘어갑니다. (단위: 초)

# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERROR MESSAGE, MOTD SETTINGS ( 메시지 설정 )
# + -------------------------------------------------------------------------------- + #

motd:
  # 대기중인 플레이어가 없지만 서버 정원이 가득 찼을 때 MOTD
  joinBlockedMOTD: "&c&l현재 서버 정원이 가득 찼습니다. 잠시만 기다려주세요."

  # 대기중 일때 뜨는 MOTD
  waitLineMOTD: "&b&l플레이어님 앞에 %remainPlayer%명이 대기중입니다."

  # 플레이어의 차례가 왔을때 뜨는 MOTD
  enterMOTD: "&c&l플레이어님의 순서입니다. %remainTime%초 안에 접속하지 않으면 다음 플레이어에게 차례가 넘어갑니다!"

message:
  # 접두사
  prefix: "[ST-Waiter]"

  # 대기열 목록 제목
  consoleListTitle: "=== 대기열 목록 ==="

  # 대기열 목록 표시 형식
  consoleListFormat: "- %ip%( %uuid% )"

  # 대기열 목록 하단
  consoleListFooter: "/대기열 목록 [<페이지>]로 더 많은 페이지를 확인해보세요!"

  # 대기열에서 플레이어를 삭제하는데 성공 했을 때
  successRemovePlayerFromWaitList: "&b성공적으로 %ip%(%nickname%)님을 대기열에서 삭제했습니다!"

  # 리로드 시 메시지
  reloadComplete: "&a리로드가 완료되었습니다."

  # 도움말 메시지
  helpMessage:
    - "&b=== 도 움 말 ==="
    - "&b/대기열 목록 - 대기열을 출력합니다."
    - "&b/대기열 삭제 [<플레이어>] - 대기열에서 플레이어를 삭제합니다."

errorMessage:

  # 펄미션이 부족할 때 메시지
  permissionDenied: "&c권한이 없습니다."

  # 대기열에 등록되었을 때 메시지
  kickMessage: "&c서버 정원이 가득 차 대기열에 등록되었습니다. 서버 설명을 새로고침하여 확인 해주세요."

  # 대기열에 등록되었지만 접속에 실패했을 때
  kickMessageWaiting: "아직 차례가 되지 않았습니다. 서버 설명(MOTD)에서 본인의 차례를 확인하세요!"

  # 대기열에 등록된 UUID와 실제 접속 UUID가 다를 때
  wrongUUID: "대기열에 등록된 UUID 와 달라 접속이 거부되었습니다."

  # 명령어를 사용할 수 없는 대상이 명령어를 사용했을 때
  wrongPlatform: "해당 명령어는 이 환경에서 사용할 수 없습니다."

  # 존재하지 않는 플레이어를 대기열에서 삭제하려 했을 때
  noExistPlayer: "&c존재하지 않는 플레이어입니다."

  # 대기열 목록이 비었을 때
  emptyWaitLine: "&c대기열이 비어있습니다."

  # 해당 페이지가 없을 때
  consoleListNoPage: "&c페이지가 없습니다."

# GUI 설정
gui:
  # 대기열 목록에 뜨는 아이템의 이름을 설정합니다
  itemDisplayName: "&b&l%uuid%"
  # 대기열 목록에 뜨는 아이템의 설명을 설정합니다.
  itemLore:
    - "IP : %ip%"
    - "순서 : %priority%"
    - "UUID : %uuid"
    - "닉네임 : %nickname%"