name: ST-Waiter
main: net.starly.waiter.WaiterMain
author: Starly Team
website: http://starly.kr/

description: Waiter Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  대기열:
    description: ST-Waiter main command

permissions:
  starly.waiter.bypass:
    description: bypass waiting line
    default: op
  starly.waiter.list:
    description: list command permission
    default: op
  starly.waiter.delete:
    description: delete command permission
    default: op
  starly.waiter.reload:
    description: reload command permission
    default: op