name: ST-Waiter
main: net.starly.waiter.WaiterMain
author: Starly Team
website: http://starly.kr/

description: Waiter Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  대기열:
    description: ST-Waiter main command
    permission: st-waiter.admin

permissions:
  st-waiter.bypass:
    description: bypass waiting line
    default: op
  st-waiter.admin:
    description: admin command permission
    default: op